[General]
bypass-system = true
skip-proxy = localhost, 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12
tun-excluded-routes = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12
dns-server = system, 223.5.5.5, 1.1.1.1

[Proxy Group]

♻️ 自动选择 = url-test, policy-regex-filter=^(?!DIRECT$|REJECT$).+$, url=http://www.apple.com/library/test/success.html, interval=400, timeout=5000, tolerance=50

🚀 节点选择 = select, DIRECT, ♻️ 自动选择

🌍 国外媒体 = select, 🚀 节点选择, 🎯 全球直连

🎬 EMBY = select, 🚀 节点选择

📲 电报信息 = select, 🚀 节点选择, 🎯 全球直连

📟 TikTok = select, 🚀 节点选择, 🎯 全球直连

🤖 OpenAi = select, 🚀 节点选择

🧮 Gemini = select, 🚀 节点选择

Ⓜ️ 微软服务 = select, 🎯 全球直连, 🚀 节点选择

🛰️ 下载服务 = select, 🎯 全球直连, 🚀 节点选择

🍎 苹果服务 = select, 🚀 节点选择, 🎯 全球直连

🎯 全球直连 = select, DIRECT, 🚀 节点选择

🛑 全球拦截 = select, REJECT, DIRECT

🍃 应用净化 = select, REJECT, DIRECT

🐟 漏网之鱼 = select, 🚀 节点选择, 🎯 全球直连


[Rule]

# =========================
# 局域网 / 本地
# =========================

RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list,🎯 全球直连

# =========================
# 解封 / 直连
# =========================

RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list,🎯 全球直连

# =========================
# 广告拦截
# =========================

RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list,🛑 全球拦截

RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list,🍃 应用净化

RULE-SET,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/adobe.list,🍃 应用净化

# =========================
# 国内服务
# =========================

RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list,🎯 全球直连

RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list,🎯 全球直连

RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list,Ⓜ️ 微软服务

RULE-SET,https://raw.githubusercontent.com/taotaoyouyou/ACL4SSR/refs/heads/main/Download.list,🛰️ 下载服务

RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list,🍎 苹果服务

# =========================
# 国际服务
# =========================

RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list,📲 电报信息

RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list,🤖 OpenAi

RULE-SET,https://raw.githubusercontent.com/taotaoyouyou/ACL4SSR/refs/heads/main/Gemini.list,🧮 Gemini

RULE-SET,https://raw.githubusercontent.com/taotaoyouyou/ACL4SSR/main/emby.list,🎬 EMBY

RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list,🌍 国外媒体

RULE-SET,https://raw.githubusercontent.com/taotaoyouyou/ACL4SSR/refs/heads/main/TikTok.list,📟 TikTok

RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list,🚀 节点选择

# =========================
# 中国大陆
# =========================

RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list,🎯 全球直连

RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list,🎯 全球直连

# =========================
# IP 地理位置
# =========================

GEOIP,LAN,🎯 全球直连

GEOIP,CN,🎯 全球直连

# =========================
# 最终规则
# =========================

FINAL,🐟 漏网之鱼
